### PR TITLE
Adding 'radians' and 'degrees' converter math utils

### PR DESCRIPTION
**Pull request by AlessandroCipolletti**
Hi, I really like this repo! I added two simple radians and degrees converter to try to submit a pull request. 
If you are open to pull requests I could add more bigger utils about cartesian plane coords :)

### CODE REVIEW

**Comment by MathisBullinger** [comment]
Hi, thanks for your interest in contributing to the project!

Some things about the project structure: Every utility must be exported from at least one of the categories, so these must be exported from the `math.ts` file. Then the readme isn't edited manually but generated by running `scripts/docs`. Before running the script please run `npm install` inside the `npm` directory (the readme generation requires typedoc). The code is formatted using the built-in Deno formatter, so run `deno fmt *.ts`.

Sorry that all of this isn't documented anywhere at the moment (I honestly didn't expect that anyone but me would be contributing to the project). I will add contribution guidelines and some automated PR checks soon to make this process smoother.

Now to the content of your PR: Yes, I think some basic unit conversion might be a good fit for the project. But with the way it's implemented I have two concerns:
1. With the function named `degrees` it's not immediately obvious that the source unit are radians. What about converting from arcminutes, arcseconds, turns, etc.?
2. When adding more units and with every unit in its own file, the number of files and exports would quickly grow out of hand when adding more units. With 5 units and conversion between all of them there would be 20 files, with 6 it would be 30 files, 7 would make 42, etc.

So what would be a good way to solve this?

Other libraries go about this by chaining multiple function calls, e.g.
```ts
convert(360).from('degree').to('radian')
```
or by encapsulating each unit in a class. But I think both would be too complex of an interface for this library and not fit in with the rest of the utilities.

So how about an interface like this?
```ts
type Angle = 'degree' | 'radian' | …

const convertAngle: (const angle: number, sourceUnit: number, targetUnit: number) => number
```

Or better yet—keeping in mind that in the future non-angular units might be added—just have one convert function that only allows converting between compatible units. That could also leverage TypeScript's type system and would fit in nicely with the other utilities:
```ts
type Unit = Angle | Length | …
type Angle = "degree" | "radian" | …
type Length = "meter" | "foot" | …

const convertUnit = <T extends Unit>(value: number, source: T, target: CompatibleUnit<T>) => {
  assert(isCompatibleUnit(source, target))
  // do unit conversion
}
```

Let me know if that's something you would be interested in working on. If not, I'll close the PR for now and create an issue to add such a utility in the future.

**Comment by AlessandroCipolletti** [comment]
Thanks for all these infos! I'll follow your guidelines for the next PR.

Ok I totally see what you mean. If you are planning to add a lot of unit converter functions, my approach to put each one in its own file would quickly become a problem.

But I also think that merging the code of all kind of unit converters inside one function could give some drawbacks.
If you reach 42 different combinations, the code would easily reach a few hundreds lines.
Code readability would certainly become harder, and this would force users to download a big chunk of code even for a simple `degrees = radians * 180 / Math.PI`.

So why not split it up to one file for each 'type' of unit conversion?
Like `convertAngleUnit`, `convertDistanceUnit`, `convertVolumeUnit` and so on.
It could be easily to maintain in the future, and it still allows us to create a generic function `convertUnit` that incapsulate all of the others.
It should just contain a bunch of `if else if` to check `source` and `target`, and then call the right unit converter utils.

What do you think ?

**Comment by MathisBullinger** [comment]
Sound like a plan. Let's create a function
```ts
const convertAngle: (value: number, from: Angle, to: Angle) => number
```
and if more unit conversions are added in the future an additional function `convertUnit` can be added that invokes the appropriate converter internally as you suggested.

> If you reach 42 different combinations, the code would easily reach a few hundreds lines.

Not necessarily. One suggestion for structuring the conversion: don't write a conversion for every unit to every unit (that would give 42 conversions for 7 units). Instead, pick one unit as the base unit and write a converter to that unit. Then convert from that base unit to the target unit, e.g:
```ts
const convertAngle = (value: number, from: Angle, to: Angle) => {
  const degree = toDegree(value, from)

  switch (to) {
    case 'someUnit': return degree * someConstant
    // ...
    default: throw TypeError(`unknown unit ${to}`)
  }
}

const toDegree: (value: number, unit: Angle) => number
```

Will close this PR for now. If you decide to implement `convertAngle` please open a new PR.

**Comment by AlessandroCipolletti** [comment]
You're right, this will be certainly more readable, and doing two conversion instead of one is not a big deal for performances in this case.

Ok I'll do this. If you prefer you can create an issue and assign it to me.

**Comment by AlessandroCipolletti** [comment]
Do you want to do unit test on `toDegree()` too ?

**Comment by MathisBullinger** [comment]
I would say only test the public API. If your test cases ensure that `convertAngle` behaves correctly then that covers `toDegree` implicitly without explicitly testing it.

**Pull request closed without merging**
