### PR TITLE
doc: fix unzipWith typo in example

### PR DESCRIPTION
**Pull request by mgred**
unzip -> unzipWith

### CODE REVIEW

**Comment by mgred** [comment]
I updated the `README.md` but couldn't commit, because the precommit hook complained about some unformatted files that do not belong to the change :man_shrugging:

**Comment by MathisBullinger** [comment]
Thanks for the PR. 
Regarding the pre-commit hook: you can format the project files by running `deno fmt *.ts` (please make sure you're running deno v1.23.2 or higher). Since you haven't made changes to any of the code and assuming you're running the correct version of deno you could also temporarily stash all unrelated changes (i.e. run `git stash --keep-index` after staging the changes you want to be part of the commit) and the pre-commit hook shouldn't make you any trouble. If nothing works—and assuming you haven't made any changes to the code—you can also always commit with `--no-verify` to bypass the hook.
Just in case you updated the README manually: The README is generated via a script from the JSDoc comments. So please run `scripts/docs` to update it after running `npm install` inside the `npm` directory.

**Comment by mgred** [comment]
@MathisBullinger Thanks for your answer, I ran the `scripts/docs` to regenerate the `README.md` already :+1: I totally forgot about the `--no-verify` flag for this case :man_facepalming:

**Review by MathisBullinger — APPROVED** [review]

**Comment by MathisBullinger** [comment]
ok then, LGTM

**Pull request merged**
